services:
  - type: web
    name: school-index-reports
    env: python
    runtime: python3.9
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn wsgi:app 